service: aws-node-typescript-sqs-standard

frameworkVersion: "3"

custom:
  esbuild:
    bundle: true
    minify: false
    target: node20
  enterprise:
    collectLambdaLogs: false
  sqs: arn:aws:sqs:us-east-1:891377350988:serveless
  stages:
    - dev
    - prod

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256 
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment: ${file(serverless/environment.yml)}
  iam:
    role: arn:aws:iam::891377350988:role/LabRole
      
functions:
  receiver:
    handler: src/receiver.handler
    events:
      - sqs: ${self:custom.sqs}
  