service: lambda-notification

frameworkVersion: "3"

custom:
  esbuild:
    bundle: true
    minify: false
    target: node20
  enterprise:
    collectLambdaLogs: false
  stages:
    - dev
    - prod

params:
  default:
    sqs: "${ssm:queue-notificacao-prd}"
  prod:
    sqs: "${ssm:queue-notificacao-prd}"
  dev:
    sqs: "${ssm:queue-notificacao-dev}"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256 
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment: ${file(serverless/environment.yml)}
   
functions:
  receiver:
    handler: src/receiver.handler
    events:
      - sqs: ${param:sqs}

  